### ISSUE TITLE
Silencer

### ISSUE THREAD

**Issue by BrutalCSEjziponken** [splewis/csgo-retakes#15]
Hey! Some players pointed out that you cant have M4 silencer without using the retakes_standardallocator. 

Like in our situation, we wanted to have a server without AWP and nades but then we also lose the silencer. My suggestion would be that the M4 menu would be implemented in the main plugin. :)

**Comment by splewis** [comment]
I purposefully left the weapon logic out of the base plugin because everyone wants something different, and don't want to create an enormously complex cvar/keyvalue structure to specify what weapons people can get and what's available. 

If you want different weapon logic, all the tools are there for you to write it without having to edit the retakes plugin, e.g. ``Retakes_SetPlayerInfo`` in [retakes.inc](https://github.com/splewis/csgo-retakes/blob/master/scripting/include/retakes.inc#L170)

And putting the m4 selection in the base plugin would complicate what's already a clean separation of concerns.
