### ISSUE TITLE
!guns dont work

### ISSUE THREAD

**Issue by theblackgem** [splewis/csgo-retakes#170]
### Expected behavior
!guns brings up a menu of guns you can choose from

### Actual behavior
When i type !guns nothing comes up and i only spawn with an AK/M4 and the default pistol.

### Steps to reproduce
- Plugin version: I don't know exact verison, i downloaded it from this github on November 10th, 2018
- Sourcemod version: 1.9
- Steps to reproduce (please be specific):Don't really know what this means, but the plugin is working perfectly fine, retake spawns are good, everything is fine except the !guns command which doesn't bring up any menu.

**Comment by splewis** [comment]
That's because the retakes plugin doesn't provide a !guns command (well it does; it just doesn't do anything on purpose).

The [retakes_standardallocator](https://github.com/splewis/csgo-retakes#retakes_standardallocator) (and the retakes_pistolallocator) plugin will provide a basic guns command and menu. If you want more advanced behavior around how weapons are given you need to write your own plugin to do it or find someone else who was.
