### ISSUE TITLE
After the upgrade, does not issue a bomb and weapons only a knife

### ISSUE THREAD

**Issue by Razer123** [splewis/csgo-retakes#172]
After the upgrade, does not issue a bomb and weapons only a knife

**Comment by TandelK** [comment]
@Razer123 I was able to solve Weapons issue that is due to Weapons , Gloves and Knife Plugin which are running pTaH Extension and currently new update broke this extension causing server to not load weapons and gloves plugin which will not give you weapons and other items. 

The only error comes after removing this plugin is after Warmup Server get crashed

**Comment by Razer123** [comment]
> @Razer123 I was able to solve Weapons issue that is due to Weapons , Gloves and Knife Plugin which are running pTaH Extension and currently new update broke this extension causing server to not load weapons and gloves plugin which will not give you weapons and other items.
> 
> The only error comes after removing this plugin is after Warmup Server get crashed

i have workers gloves and knife, and the weapon does not give

**Comment by Razer123** [comment]
deleted PTaH all working

**Comment by TandelK** [comment]
Close the issue
