### ISSUE TITLE
Issue with team balancing favoring Ts 

### ISSUE THREAD

**Issue by alexrock88** [splewis/csgo-retakes#196]
Hello, this will probably be a simple fix or something I did wrong, but while running your code (which aside from this has been perfect btw) I have been having an issue with the game favoring Ts (say 4Ts vs 3CTs) and my players are starting to get pretty annoyed. I am rather new coding so I haven't been able to locate what the issue may be at this point but was hoping to get a little help if that is ok. 

Thank you!

**Comment by RavageCS** [comment]
https://github.com/splewis/csgo-retakes/blob/master/scripting/retakes.sp#L154

**Comment by lazhoroni** [comment]
While cvar is 0.425, it is 4 T - 6 CT. Cvar will do 5 T - 5 CT will do? 
I did 0.499. This time it was 4 people - 4 T - 4 CT. I want 3 T - 5 T to be 8 people.

**Comment by splewis** [comment]
There's 2 cvars:
sm_retakes_ratio_constant
sm_retakes_maxplayers

You can set them to whatever you want in cfg/sourcemod/retakes/retakes.cfg.

If your problem is a bug with those (e.g. more than `sm_retakes_maxplayers` players can connect, or players are bypassing the ratio cvar somehow), then steps to reproduce will be needed.

**Comment by borzaka** [comment]
You can't have different `sm_retakes_ratio_constant` setting based on how many players are in the game. You can, but you have to manually change based on the player count on the server.

I would say `0.45` is a good value;
- 8 players: 4v4
- 10 player: 5v5
