### ISSUE TITLE
spawn bugs, max players bug and bots bug

### ISSUE THREAD

**Issue by flashing1998** [splewis/csgo-retakes#221]
spawn on vertigo are not working i think due to map update, players are stuck inside the walls and bomb is also inside the ground
another random issue i found was i have limited max players to 10 in a match, but there were 11 players playing 5CT 6T
another issue is bots randomly joining the teams or the spectate

**Comment by borzaka** [comment]
- Use the spawns from this issue: #214
I have already made a PR, it will updated soon in the repo
- Try to change the `sm_retakes_ratio_constant` setting to `0.45`
Check this issue for more info: #196
- The bot issue:  there are many known bugs around bots, you have to manage yourself the bot things, for example with this plugin: [bot_quota 0 enforcer](https://forums.alliedmods.net/showthread.php?t=237004)
It will kick any bots who try to join the game.

**Comment by flashing1998** [comment]
bro your vertigo spawns are not working cts and ts are spwaning beside each other

**Comment by borzaka** [comment]
Well bro, first it's not my spawns, second it's working perfectly on my servers. So, you should check your configs and restart your servers when the new spawns are installed correctly.

Third, you can always make your own spawns at any time which works for your needs.

**Comment by splewis** [comment]
I don't endorse any spawn files. If you don't like them, that's not a bug, that's a reason for you to go make your own files.

On the player numbers, sounds like this bug: https://github.com/splewis/csgo-retakes/issues/204

For bots, my servers have always been fine with `bot_quota 0` and no extra plugins. Regardless, it's not the 'retakes' plugin's job to kick bots, by design.
