### ISSUE TITLE
PrintHintTextToAll

### ISSUE THREAD

**Issue by Joob** [splewis/csgo-retakes#32]
Hi.. How can I put this information on center of monitor ? as you had in the previous version ..
Regards..

**Comment by splewis** [comment]
This plugin never used hint texts for any information.

**Comment by Joob** [comment]
yes, I know.. but I would like you had in the previous version .. when the round start, give you information about SITE A or B .. on center monitor.. u know ?

**Comment by splewis** [comment]
That wasn't in any previous version of this project. You're thinking of a different retakes plugin.

**Comment by Joob** [comment]
no no.. don't u remember this..

---------------
public Action:Timer_PrintHintSite(Handle:timer, any:site)
{
	if(GetEngineTime() - gf_StartRoundTime >= 3)
		return Plugin_Stop;
	PrintHintTextToAll("\n<font size='22'>BOMBSITE IS </font><font size='22' color='#E22C56'>%s</font>", site == SITEA ? "A":"B");
	return Plugin_Continue;
}
---------------

**Comment by splewis** [comment]
No, I don't, because it was never a part of this plugin. It was part of someone else's plugin attempting to replicate mine before it was open source.

**Comment by Joob** [comment]
Hmm correct.. exactly..
can u write a simple code for this info ? (on monitor center)

**Comment by splewis** [comment]
There's been a [request](https://github.com/splewis/csgo-retakes/issues/4) to add it for 9 months. If someone wants to add it, they are free to make a pull request. I didn't do it myself since I don't consider it important and don't want to mess with having the HTML-formatted colors in the hint text and have another piece of text to translate.
