### ISSUE TITLE
New gun

### ISSUE THREAD

**Issue by BrutalCSEjziponken** [splewis/csgo-retakes#43]
– Added a new secondary weapon, the R8 Revolver, which occupies the Desert Eagle loadout slot.

**Comment by splewis** [comment]
The only thing that would need to be changed is the [https://github.com/splewis/csgo-retakes/blob/master/scripting/retakes_pistolallocator.sp](pistolallocator) plugin, but since the new weapon costs $850 it is irrelevant to pistol rounds, which is what that plugin simulates - so there shouldn't be any changes needed.
