### ISSUE TITLE
Turning "retakes" into "takes"

### ISSUE THREAD

**Issue by socokal** [splewis/csgo-retakes#55]
If I wanted to have a "take"mode (i.e. T's trying to attack a certain bomb site guarded by CT's) could I just have a disabled folder with the alternative spawn points and then just swap them out and change the round timer.

**Comment by spot88** [comment]
The thing you are looking for is B-rush. And i would love if splewis would make one of those as well. 
Your Retake plugin is awesome! So i would not doubt that a B-rush plugin would be any problem for you!

**Comment by HalfEatenPie** [comment]
They are practically the same thing, retakes and B-rush.  Except that retakes are probably better as there's an actual end to the round.  If your B-take fails then you can always rotate.  

Maybe the ability to switch weapons (such as maybe defending with M4s instead of AKs) would be nice, but in the end I see B-rush as the more inferior version of Retakes.

**Comment by spot88** [comment]
But it's not, B-rush is a good and old "plugin" from 1.6. 
It's awesome..

**Comment by splewis** [comment]
You can do whatever you want with the spawns. It probably wouldn't work well since the T's could just run to whatever site, though.
